# Generated by Django 3.1 on 2020-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200819_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='empty_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
