# Generated by Django 3.1 on 2020-08-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161020_2224'),
        ('shortener', '0003_auto_20200819_2301'),
    ]

    operations = [
    ]
