# Generated by Django 3.1 on 2020-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
